# Generated by Django 2.2 on 2019-04-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_auto_20190426_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='wav',
            name='filename',
            field=models.CharField(default='NoName', max_length=20),
        ),
        migrations.AlterField(
            model_name='wav',
            name='location',
            field=models.CharField(default='NofilePath', max_length=200),
        ),
    ]
