# Generated by Django 2.2 on 2019-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_auto_20190426_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_processed',
            field=models.CharField(default='no procession', max_length=200),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_raw',
            field=models.CharField(default='notext', max_length=200),
        ),
    ]
